version: '3.7'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: myapp-server
    container_name: app-node-server
    #command: /usr/src/app/node_modules/.bin/nodemon server.js
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5002:5002"
    environment:
      - NODE_ENV=development
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: myapp-client
    container_name: app-react-client
    command: npm start
    volumes:
      - ./client/:/usr/app
      - /usr/app/node_modules
    ports:
      - "3003:3000"
    networks:
      - app-network

networks:
    app-network:
        driver: bridge
