test1:
  outputs:
    dev:
      type: postgres
      threads: 1
      host: "{{ env_var('DBT_DEV_HOST') }}"
      port: "{{ env_var('DBT_DEV_PORT') }}"
      user: "{{ env_var('DBT_DEV_USER') }}"
      pass: "{{ env_var('DBT_DEV_PASSWORD') }}"
      dbname: "{{ env_var('DBT_DEV_DBNAME') }}"
      schema: "{{ env_var('DBT_DEV_SCHEMA') }}"

    prod:
      type: postgres
      threads: 1
      host: "{{ env_var('DBT_PROD_HOST') }}"
      port: "{{ env_var('DBT_PROD_PORT') }}"
      user: "{{ env_var('DBT_PROD_USER') }}"
      pass: "{{ env_var('DBT_PROD_PASSWORD') }}"
      dbname: "{{ env_var('DBT_PROD_DBNAME') }}"
      schema: "{{ env_var('DBT_PROD_SCHEMA') }}"

  target: "{{ env_var('DBT_TARGET') }}"
